### ISSUE TITLE
Editor's config files in repository

### ISSUE THREAD

**Issue by n3wborn** [AcalaNetwork/acala.js#184]
Hi ! First, thanks for all the job done, Acala is amazing and having tools like acala.js really helps. 

This is not really an issue and as I'm really noob in dev I know my mind about how this repo is managed my opinion doesn't count for much  but I thought having editor's config/backup files in a repository wasn't a good thing. So I'm a bit confused seeing .vscode here.

I forked, did a new branch and did two commits (updated .gitignore and resubmit files) so, if you wish, I will be glad to push a PR :)

Thanks !

**Comment by xlc** [comment]
Please learn more about editorconfig here https://editorconfig.org
We intent to have those files committed to ensure the text format in the repo.

**Comment by n3wborn** [comment]
> Please learn more about editorconfig here https://editorconfig.org
> We intent to have those files committed to ensure the text format in the repo.

Sorry I did not explain correctly or gave the best title. . I know I have to keep .editorconfig is important (I do use it in neovim).  I was just talking about .vscode file (and other editors config or backup files).
If you mind checking [these](https://github.com/n3wborn/acala.js/commit/beee509af8bcb2faee29e6ccaf5bdd45aa5c165b) [commits](https://github.com/n3wborn/acala.js/commit/3eb927a28e7adb8f92ce53d19d7cba1275b62745).

Sorry for wasting time if I'm wrong

**Comment by xlc** [comment]
Yes we want to have it. Here are some explanations https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control
