### ISSUE TITLE
polkadot.js.org errors decoding block 493009

### ISSUE THREAD

**Issue by dzhelezov** [AcalaNetwork/acala.js#199]
Polkadot.js explorer is failing to decode block 493009. Navigating to the link https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkarura-rpc-1.aca-api.network#/explorer/query/493009

gives

```
Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: decodeU8a: failed at 0x0f012472f4c57b61… on signature: {"_enum":{"Ed25519":"Ed25519Signature","Sr25519":"Sr25519Signature","Ecdsa":"EcdsaSignature"}}:: Unable to create Enum via index 15, in Ed25519, Sr25519, Ecdsa
```

Probably due to the recent type updates for Kusama

**Comment by xlc** [comment]
Works for me. We have just updated acala.js version https://github.com/polkadot-js/apps/pull/6086
Can you try again?

**Comment by dzhelezov** [comment]
Yes looks good, thanks!
