### ISSUE TITLE
tokens_queryExistentialDeposit not decorated in 2.3.3

### ISSUE THREAD

**Issue by timbrinded** [AcalaNetwork/acala.js#285]
## Description

When using acala.js the following line is printed whenever I connect to a provider:
```
2022-02-21 15:16:30        API/INIT: RPC methods not decorated: tokens_queryExistentialDeposit
```

Tested on `ghcr.io/acalanetwork/karura-runtime:pr-1914` (v2.3.3)

## Steps to recreate
![image](https://user-images.githubusercontent.com/79199034/154983653-d3f3df73-6c14-4f9b-9948-1ef51c919564.png)
![image](https://user-images.githubusercontent.com/79199034/154983695-4b534062-817a-404c-95e4-62f8c2628e8f.png)

![image](https://user-images.githubusercontent.com/79199034/154983752-9f3721ac-dce3-4ca4-8155-8cd2a117f795.png)

**Comment by zjb0807** [comment]
```
API/INIT: RPC methods not decorated: evm_blockLimits, evm_call, evm_estimateResources, oracle_getAllValues, oracle_getValue, tokens_queryExistentialDeposit
```

**Comment by timbrinded** [comment]
No longer seen
