### ISSUE TITLE
How to get asset decimals from the AssetRegistry for all Acala/Karura assets

### ISSUE THREAD

**Issue by sourabhniyogi** [AcalaNetwork/acala.js#293]
How can we get asset _decimals_  for _all_ assets with acala.js / polkadot.js programmatically like this ERC20 => asset mapping?
https://github.com/AcalaNetwork/Acala/blob/7a29682ed20b63d21f15328acce68422a181f4f3/modules/asset-registry/src/lib.rs#L765-L785
There are `AssetRegistered` events of `AssetMetadata` type in the `AssetRegistry` module:
https://acala.subscan.io/runtime/AssetRegistry?version=2034
but there are _no_ events in Acala:
https://acala.subscan.io/event?address=&module=assetregistry&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=2034
the way there are only _some_ in Karura:
https://karura.subscan.io/event?address=&module=assetregistry&event=all&startDate=&endDate=&startBlock=&endBlock=&timeType=date&version=2040
Neither of them are comprehensive.  We do not want to hardcode 10, 12, etc.  and wish to cover all the existing cases and new cases as new assets are added to the asset registry.
```
 {"Token":"BNC"}                             
 {"Token":"KAR"}                             
 {"Token":"KINT"}                            
 {"Token":"KSM"}                             
 {"Token":"KUSD"}                            
 {"Token":"LKSM"}                            
 {"Token":"TAI"}                             
 {"Token":"VSKSM"}                           
 {"Token":"ACA"}                             
 {"Token":"AUSD"}                            
 {"Token":"DOT"}             
 {"ForeignAsset":"0"}                        
 {"ForeignAsset":"1"}                        
 {"ForeignAsset":"2"}                        
 {"StableAssetPoolToken":"0"}                
 {"LiquidCrowdloan":"13"}                    
 [{"Token":"ACA"},{"Token":"AUSD"}]          
 [{"Token":"AUSD"},{"LiquidCrowdloan":"13"}] 
 [{"Token":"DOT"},{"LiquidCrowdloan":"13"}]  
 [{"Token":"KAR"},{"Token":"KSM"}]           
 [{"Token":"KAR"},{"Token":"LKSM"}]          
 [{"Token":"KSM"},{"ForeignAsset":"0"}]      
 [{"Token":"KSM"},{"Token":"LKSM"}]          
 [{"Token":"KUSD"},{"ForeignAsset":"0"}]     
 [{"Token":"KUSD"},{"Token":"BNC"}]          
 [{"Token":"KUSD"},{"Token":"KSM"}]          
 [{"Token":"KUSD"},{"Token":"LKSM"}]         
```

**Comment by zqhxuyuan** [comment]
the reason Acala has no events is because Acala haven't register any asset yet. you can query `assetRegistry.assetMetadatas` to get all asset-registry metadata info:
```
const ent = await api.query.assetRegistry.assetMetadatas.entries();
ent.forEach(([{ args: [asset] }, value]) => {
  console.log(`${asset}: ${value.toHuman().symbol}, ${value.toHuman().decimals}`);
});
```
but the result only shows assets registry as kind of foreign asset, some token like `KSM,KAR,KUSD,LKSM,BNC,` is not in the result.

**Comment by sourabhniyogi** [comment]
Ok, we found the "native" assets in system.properties and can use the first asset in a liquidity pair to get the liquidity pair's decimals.  Is 
```
 {"LiquidCrowdloan":"13"}       
 ```
 going to be registered in `assetRegistry.assetMetadatas`, or appear in system.properties soon?  It is not listed here:
 ```
 curl -k -H "Content-Type: application/json" https://acala-polkadot.api.onfinality.io/public-rpc  -d '{"jsonrpc":"2.0","method":"system_properties","params":[],"id":1}'
{"jsonrpc":"2.0","result":{"ss58Format":10,"tokenDecimals":[12,12,10,10],"tokenSymbol":["ACA","AUSD","DOT","LDOT"]},"id":1}
```

**Comment by qwer951123** [comment]
we support a SDK to query all tokens
```bash
yarn add @acala-network/sdk@4.0.2-21
```
```javascript
const api = ... // create karura api
const wallet = new Wallet(api)
const allTokens = await wallet.getTokens()

allTokens.forEach((token) => {
  console.log(token.decimals)
  console.log(token.symbol)
}
```

**Comment by sourabhniyogi** [comment]
Thank you, that is comprehensive!
