### ISSUE TITLE
Update how totalStaking is Calculated

### ISSUE THREAD

**Issue by ferrell-code** [AcalaNetwork/acala.js#384]
Can just read totalStakingBonded from storage now: https://github.com/AcalaNetwork/Acala/pull/2172

Not important as current way is still correct

https://github.com/AcalaNetwork/acala.js/blob/13054811db5ce59688e0e9011962acae6b6ff6be/packages/sdk/src/homa/index.ts#L221

**Comment by qwer951123** [comment]
done
