### ISSUE TITLE
Token provider returns foreign asset instead of erc20 in case both have same symbol

### ISSUE THREAD

**Issue by nohaapav** [AcalaNetwork/acala.js#470]
Hi guys, we found one issue yesterday trying to integrate WETH xcm transfer from acala <-> hydradx. If there are multiple assets with the same symbol, first one is being returned. In our case: 

```
 [
    [
      {
        ForeignAssetId: 6
      }
    ]
    {
      name: Wrapped Ether
      symbol: WETH
      decimals: 18
      minimalBalance: 500,000,000,000,000
   
```

instead of erc20 token so balance returned by wallet is incorrect. 

Would it be possible to either return list of balances covering all the tokens that match token symbol or pass some sort of filter fn in wallet options to handle correct filtering of tokens ? 

Here is the line causing the troubles:
https://github.com/AcalaNetwork/acala.js/blob/master/packages/sdk/src/wallet/token-provider/acala.ts#L147

**Comment by qwer951123** [comment]
The WETH and WBTC under the ForeignAssetId module have been deprecated and now a simple filter has been added to hide these two tokens.
