### ISSUE TITLE
Acala vs Karura swap sdk

### ISSUE THREAD

**Issue by dudo50** [AcalaNetwork/acala.js#509]
Do Acala and Karura have the same swap SDK? We are unable to find dApps in github repositories.

We are implementing the XCM router package and we wish to map every native exchange to give users the ability to swap while XCM. 

Thank you in advance.

**Comment by xlc** [comment]
The swap function is the same between Acala and Karura

**Comment by dudo50** [comment]
> The swap function is the same between Acala and Karura

@xlc 

Does it contain assets for both Acala and Karura? Or do these swap-supported assets have to be imported from elsewhere? Thanks in advance.

**Comment by xlc** [comment]
The assets and trading pairs are queried from onchain state. acala.js provides the SDK to perform those queries

**Comment by dudo50** [comment]
@xlc could you point me to it via link? Many thanks!

**Comment by xlc** [comment]
We don't have lots docs but hopefully the code is easy enough to understand https://github.com/AcalaNetwork/acala.js/blob/master/packages/sdk-swap/src/dex.ts

**Comment by dudo50** [comment]
Got it working. Thanks!
